export const COMMANDS = [
  "momentum goal start <goal.md> [--repo <path>] [--foreground] [--runner <profile>] [--from-source <source-item-id>] [--data-dir <path>] [--json]",
  "momentum status [goal-id] [--data-dir <path>] [--json]",
  "momentum logs <goal-id> [--iteration <n>] [--data-dir <path>] [--json]",
  "momentum handoff <goal-id> [--data-dir <path>] [--json]",
  "momentum source list [--adapter <kind>] [--data-dir <path>] [--json]",
  "momentum source get <source-item-id> [--data-dir <path>] [--json]",
  "momentum source link <source-item-id> --goal <goal-id> [--data-dir <path>] [--json]",
  "momentum source unlink <source-item-id> [--data-dir <path>] [--json]",
  "momentum source reconcile linear [--project <id-or-name>] [--milestone <id-or-name>] [--dry-run] [--max-pages <n>] [--linear-endpoint <url>] [--linear-page-size <n>] [--data-dir <path>] [--json]",
  "momentum worker run [--worker-id <id>] [--data-dir <path>] [--json]",
  "momentum daemon start [--max-loop-iterations <n>] [--max-idle-cycles <n>] [--poll-interval-ms <ms>] [--data-dir <path>] [--json]",
  "momentum daemon stop [--now] [--reason <text>] [--data-dir <path>] [--json]",
  "momentum daemon status [--data-dir <path>] [--json]",
  "momentum project status [--source <adapter>] [--project <id-or-name>] [--milestone <id-or-name>] [--stale-threshold-hours <n>] [--intent-stale-threshold-days <n>] [--data-dir <path>] [--json]",
  "momentum recovery clear <goal-id> [--reason <text>] [--data-dir <path>] [--json]",
  "momentum evidence ingest --path <file-or-dir> [--goal <id>] [--source-item <id>] [--data-dir <path>] [--json]",
  "momentum evidence list [--goal <id>] [--source-item <id>] [--source <source>] [--type <type>] [--limit <n>] [--data-dir <path>] [--json]",
  "momentum workflow import --path <run-dir> [--data-dir <path>] [--json]",
  "momentum workflow status [<run-id>] [--state <state>] [--filter <active|blocked|completed|imported>] [--limit <n>] [--data-dir <path>] [--json]",
  "momentum workflow handoff <run-id> [--data-dir <path>] [--json]",
  "momentum workflow run approve <run-id> --approval-boundary <boundary> --phrase <text> [--actor <name>] [--artifact-path <path>] [--artifact-digest <sha256>] [--data-dir <path>] [--json]",
  "momentum workflow run decide <gate-id> --action <action> --actor <name> [--mode <operator|delegated>] [--note <text>] [--data-dir <path>] [--json]",
  "momentum workflow run list [--state <state>] [--filter <active|blocked|completed|imported>] [--approval-boundary <boundary>] [--repo <path>] [--issue-scope <identifier>] [--updated-since <ms>] [--updated-until <ms>] [--limit <n>] [--data-dir <path>] [--json]",
  "momentum workflow run update-step <run-id> --step <step-id> --state <approved|succeeded|skipped|failed|blocked|canceled> --reason <text> [--actor <name>] [--evidence-pointer <ref>] [--ledger-pointer <ref>] [--data-dir <path>] [--json]",
  "momentum workflow run clear-recovery <run-id> [--evidence-pointer <ref>] [--ledger-pointer <ref>] [--data-dir <path>] [--json]",
  "momentum workflow run monitor <run-id> [--advance] [--data-dir <path>] [--json]",
  "momentum workflow run logs <run-id> [--data-dir <path>] [--json]",
  "momentum workflow run start --run-id <id> --repo <path> --objective <text> [--definition <key>] [--definition-version <n>] [--approval-boundary <boundary>] [--skill-revision <text>] [--issue-scope <identifier>] [--profile <name>] [--data-dir <path>] [--json]",
  "momentum workflow run start-coding --run-id <id> --repo <path> --objective <text> [--approval-boundary <boundary>] [--skill-revision <text>] [--issue-scope <identifier>] [--profile <name>] [--steps-json <json>] [--definition-version <n>] [--data-dir <path>] [--json]",
  "momentum workflow run preview-coding --run-id <id> --repo <path> --objective <text> [--approval-boundary <boundary>] [--skill-revision <text>] [--issue-scope <identifier>] [--profile <name>] [--steps-json <json>] [--definition-version <n>] [--data-dir <path>] [--json]",
  "momentum intent list [--status <status>] [--adapter <kind>] [--type <intent-type>] [--goal <goal-id>] [--source-item <id>] [--evidence-record <id>] [--limit <n>] [--data-dir <path>] [--json]",
  "momentum intent get <intent-id> [--data-dir <path>] [--json]",
  "momentum intent apply <intent-id> --reason <text> [--repo <path>] [--external-apply] [--data-dir <path>] [--json]",
  "momentum intent skip <intent-id> --reason <text> [--data-dir <path>] [--json]",
  "momentum intent cancel <intent-id> --reason <text> [--data-dir <path>] [--json]",
  "momentum doctor [--repo <path>] [--data-dir <path>] [--json]"
];
