const NODE_MAX_TIMER_DELAY_MS = 2_147_483_647;
const PROCESS_SUPERVISOR_WATCHDOG_MARGIN_MS = 30_000;

export const MAX_BUILT_IN_PROCESS_TIMEOUT_MS =
  Math.floor(
    (NODE_MAX_TIMER_DELAY_MS - PROCESS_SUPERVISOR_WATCHDOG_MARGIN_MS) / 1_000,
  ) * 1_000;
export const MAX_BUILT_IN_PROCESS_TIMEOUT_SEC =
  MAX_BUILT_IN_PROCESS_TIMEOUT_MS / 1_000;
